package com.renshiproject.dataobject;

public class AdministratorInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administratorinfo.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administratorinfo.password
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administratorinfo.id
     *
     * @return the value of administratorinfo.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administratorinfo.id
     *
     * @param id the value for administratorinfo.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administratorinfo.password
     *
     * @return the value of administratorinfo.password
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administratorinfo.password
     *
     * @param password the value for administratorinfo.password
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}