package com.renshiproject.dataobject;

public class AttendanceDO extends AttendanceDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.absence
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer absence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.late
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer late;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.employee_name
     *
     * @return the value of attendance.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.employee_name
     *
     * @param employeeName the value for attendance.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.dept_name
     *
     * @return the value of attendance.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.dept_name
     *
     * @param deptName the value for attendance.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setDeptName(Integer deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.position
     *
     * @return the value of attendance.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.position
     *
     * @param position the value for attendance.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.absence
     *
     * @return the value of attendance.absence
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getAbsence() {
        return absence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.absence
     *
     * @param absence the value for attendance.absence
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setAbsence(Integer absence) {
        this.absence = absence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.late
     *
     * @return the value of attendance.late
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getLate() {
        return late;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.late
     *
     * @param late the value for attendance.late
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setLate(Integer late) {
        this.late = late;
    }
}