package com.renshiproject.dataobject;

import java.util.Date;

public class AttendanceDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.employee_id
     *
     * @return the value of attendance.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.employee_id
     *
     * @param employeeId the value for attendance.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.time
     *
     * @return the value of attendance.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.time
     *
     * @param time the value for attendance.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}