package com.renshiproject.dataobject;

import java.util.Date;

public class Award_punishDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.award_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String awardReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.award_money'
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String awardMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.punish_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String punishReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer punishMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award_punish.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.id
     *
     * @return the value of award_punish.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.id
     *
     * @param id the value for award_punish.id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.employee_id
     *
     * @return the value of award_punish.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.employee_id
     *
     * @param employeeId the value for award_punish.employee_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.employee_name
     *
     * @return the value of award_punish.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.employee_name
     *
     * @param employeeName the value for award_punish.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.dept_name
     *
     * @return the value of award_punish.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.dept_name
     *
     * @param deptName the value for award_punish.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setDeptName(Integer deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.position
     *
     * @return the value of award_punish.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.position
     *
     * @param position the value for award_punish.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.award_reason
     *
     * @return the value of award_punish.award_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getAwardReason() {
        return awardReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.award_reason
     *
     * @param awardReason the value for award_punish.award_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setAwardReason(String awardReason) {
        this.awardReason = awardReason == null ? null : awardReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.award_money'
     *
     * @return the value of award_punish.award_money'
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getAwardMoney() {
        return awardMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.award_money'
     *
     * @param awardMoney' the value for award_punish.award_money'
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setAwardMoney(String awardMoney) {
        this.awardMoney = awardMoney == null ? null : awardMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.punish_reason
     *
     * @return the value of award_punish.punish_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getPunishReason() {
        return punishReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.punish_reason
     *
     * @param punishReason the value for award_punish.punish_reason
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPunishReason(String punishReason) {
        this.punishReason = punishReason == null ? null : punishReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.punish_money
     *
     * @return the value of award_punish.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getPunishMoney() {
        return punishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.punish_money
     *
     * @param punishMoney the value for award_punish.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPunishMoney(Integer punishMoney) {
        this.punishMoney = punishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award_punish.time
     *
     * @return the value of award_punish.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award_punish.time
     *
     * @param time the value for award_punish.time
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}