package com.renshiproject.dataobject;

public class DepartmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.manager_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String managerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_id
     *
     * @return the value of department.dept_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_id
     *
     * @param deptId the value for department.dept_id
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_name
     *
     * @param deptName the value for department.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.manager_name
     *
     * @return the value of department.manager_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.manager_name
     *
     * @param managerName the value for department.manager_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }
}