package com.renshiproject.dataobject;

public class WageDO extends WageDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.basic_wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Float basicWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.award
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer award;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Integer punishMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wage.salary
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    private Float salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.employee_name
     *
     * @return the value of wage.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.employee_name
     *
     * @param employeeName the value for wage.employee_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.dept_name
     *
     * @return the value of wage.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.dept_name
     *
     * @param deptName the value for wage.dept_name
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.position
     *
     * @return the value of wage.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.position
     *
     * @param position the value for wage.position
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.basic_wage
     *
     * @return the value of wage.basic_wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Float getBasicWage() {
        return basicWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.basic_wage
     *
     * @param basicWage the value for wage.basic_wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setBasicWage(Float basicWage) {
        this.basicWage = basicWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.award
     *
     * @return the value of wage.award
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.award
     *
     * @param award the value for wage.award
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setAward(Integer award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.punish_money
     *
     * @return the value of wage.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Integer getPunishMoney() {
        return punishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.punish_money
     *
     * @param punishMoney the value for wage.punish_money
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setPunishMoney(Integer punishMoney) {
        this.punishMoney = punishMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wage.salary
     *
     * @return the value of wage.salary
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public Float getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wage.salary
     *
     * @param salary the value for wage.salary
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    public void setSalary(Float salary) {
        this.salary = salary;
    }
}