package com.renshiproject.dao;

import com.renshiproject.dataobject.AttendanceDO;
import com.renshiproject.dataobject.AttendanceDOKey;

public interface AttendanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int deleteByPrimaryKey(AttendanceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insert(AttendanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insertSelective(AttendanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    AttendanceDO selectByPrimaryKey(AttendanceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKeySelective(AttendanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKey(AttendanceDO record);
}