package com.renshiproject.dao;

import com.renshiproject.dataobject.Award_punishDO;

public interface Award_punishDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insert(Award_punishDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insertSelective(Award_punishDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    Award_punishDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKeySelective(Award_punishDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award_punish
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKey(Award_punishDO record);
}