package com.renshiproject.dao;

import com.renshiproject.dataobject.DepartmentDO;

public interface DepartmentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insert(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insertSelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    DepartmentDO selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKeySelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKey(DepartmentDO record);
}