package com.renshiproject.dao;

import com.renshiproject.dataobject.WageDO;
import com.renshiproject.dataobject.WageDOKey;

public interface WageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int deleteByPrimaryKey(WageDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insert(WageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int insertSelective(WageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    WageDO selectByPrimaryKey(WageDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKeySelective(WageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wage
     *
     * @mbg.generated Sat Jun 29 09:14:49 CST 2019
     */
    int updateByPrimaryKey(WageDO record);
}